### ISSUE TITLE
Can't serve locally anymore

### ISSUE THREAD

**Issue by adreawheaton** [Riverscapes/PBR#10]
Hey @MattReimer and @philipbaileynar 

I'm trying to serve the PBR website locally to make some edits... I get this error:
```
 Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
```

What am I doing wrong?

**Comment by MattReimer** [comment]
Hi @adreawheaton,

This one's an easy fix

Make sure your local Gemfile is up to date:

```
# A note about this GEM file:
# This gemfile is only to help you run `bundle exec jekyll serve` on your
# local machine. It is not used in any way by the build system
# frozen_string_literal: true

source "https://rubygems.org"
gem "jekyll", "3.9.0"
gem "jekyll-remote-theme", "0.4.2"
gem "kramdown-parser-gfm", "1.1.0"
```

then run `bundle install` and then `bundle update jekyll` if you get an error. 

That should do it. let me know if that doesn't fix things.

**Comment by adreawheaton** [comment]
@MattReimer that did the trick, thanks!

**Comment by joewheaton** [comment]
@MattReimer thanks for the 'easy fix'. However, I don't think we're done.  Am I write in thinking this breaks _all_ local servers for everyone on every site? As such, how would users know they need to update their GEM file for every repo, because the `.gitignore` file for every one of these ignores the `*.gem` file!

In other words, you pushed a big update to all the websites (thanks BTW), but for those following [our instructions on how to serve a site locally](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/testing_locally.html#5-serving-a-site-locally) we give them no warning about this! 

It seems to me we need to:
- [ ] update the [documentation](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/testing_locally.html#5-serving-a-site-locally) to tell people what to do with GEM files
- [ ] update the [template theme](https://github.com/Riverscapes/riverscapes-jekyll-theme/releases/latest) so it has correct GEM file (maybe you have)
- [ ] alert authors of active tool sites they need to apply this fix?

The local testing is fundamental and something I've been pushing and encouraging folks to do. This minimally includes @adreawheaton , @nick4rivers , @wally-mac , @tyler1218hatch , @kbartelt , and others. Am I missing something @philipbaileynar and @MattReimer? I raise this also so we think about how updates that get pushed centrally to the theme (intent being so people don't need to do a bunch of manual stuff like this) impact individuals. Thoughts?

**Comment by joewheaton** [comment]
Maybe I am wrong... maybe you have updated the GEM file for everyone? But they still have to  run `bundle install` and then `bundle update jekyll` if you get an error. Do they need to do this once on their machine, or for all repos on their local machine?

**Comment by joewheaton** [comment]
> Maybe I am wrong... maybe you have updated the GEM file for everyone? But they still have to run `bundle install` and then `bundle update jekyll` if you get an error. Do they need to do this once on their machine, or for all repos on their local machine?

Anecdotally, for me, it appears I have to run these for every repo.

**Comment by MattReimer** [comment]
I updated every Gem file I could find (pretty thoroughly I think) but I may have missed some in repos beyond my vision. 

This kind of upgrade is going to be a regular thing and having people run `bundle update jekyll` is definitely going to be something that we do from time to time. It's a tricky thing because minor security updates will happen and I'm not sure about the best communications mechanism to get this to people. I also don't control what's installed on their machine so that's challenging.

I did put out a new release of the starter site with some notes:
https://github.com/Riverscapes/riverscapes-jekyll-theme/releases

If you imagine a document writer sitting down, running git pull, starting Jekyll and seeing this error where is the first place they would look for help? Should we have a troubleshooting section on the website? 

Again, it's really challenging because the upgrade insttructions may vary from release to release depending on what's being patched.

Totally open to suggestions here.

**Comment by joewheaton** [comment]
> I updated every Gem file I could find (pretty thoroughly I think) but I may have missed some in repos beyond my vision.
> 

I think the only ones I have, that were not updated were outside the Riverscapes Consortium (i.e. my classes), so that's on me and doesn't worry me. Makes sense.

> This kind of upgrade is going to be a regular thing and having people run `bundle update jekyll` is definitely going to be something that we do from time to time. It's a tricky thing because minor security updates will happen and I'm not sure about the best communications mechanism to get this to people. I also don't control what's installed on their machine so that's challenging.
> 
> I did put out a new release of the starter site with some notes:
> https://github.com/Riverscapes/riverscapes-jekyll-theme/releases
> 

I like that. I marked this as done in check list above.

> If you imagine a document writer sitting down, running git pull, starting Jekyll and seeing this error where is the first place they would look for help? Should we have a troubleshooting section on the website?
> 

Great question. To me, the first place I would go back to is the instructions on running a local server. So I think if its there, we're good. This is really only a problem for the small (for now) audience of folks updating websites. @philipbaileynar what do you think?

> Again, it's really challenging because the upgrade insttructions may vary from release to release depending on what's being patched.
> 
> Totally open to suggestions here.

I hear you... maybe your suggestion of somewhere having a page that documents updates to the theme? It is a challenge. This is all pretty minor, just wanting to make sure we have a place we document it and workflow that is more user maintenance free for you. I have no problems with users running into these problems. I just want when they inquire, for the solution to not be buried and documented in a ticket like this, but instead your response links them to the place they need to look where solution is documented.  If we train users on where to look, they're sorted for next time. If we act like they should know or only bury fix in some random ticket, we're not making it easy. Make sense?

**Comment by MattReimer** [comment]
@joewheaton yeah I think so. My preference would be for me to put upgrade [notes on the release](https://github.com/Riverscapes/riverscapes-jekyll-theme/releases) and then put something like "Not working? Check the release notes" and then a link there. We don't want our instructions to get too distributed becauss then forgetting to update some of the docs becomes kind of inevitable. 

The whole thing is kind of bad because we're at the whim of whatever jekyll version Github says they want to use and the Ruby community, either of which can change at any moment.

The more I think of it the more I think that having the client at the exact same version as the server is kind of a futile endeavour. Building locally should really only be a rough preview to help you write docs. As long as there aren't severe bugs there's no reason it can't lag a few versions behind the server. That way we can do this sort of pain as little as possible, except when there's a big shift. 

The next big shift I can foresee is upgrading to Jekyll 4.0 but, so far there's no ETA on that.
