### ISSUE TITLE
Punchlist of Canvas Site Issues to Fix

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/PBR#18]
## [WATS 5620](http://lowtechpbr.restoration.usu.edu/workshops/2021/USU/WATS-5620/)
- [x] Adjust due dates of assignments for 2022

**Comment by mikeclawson** [comment]
@joewheaton I've changed them so that everything from Module 1 (lectures, readings, and quiz) are all due before the first class on the 11th, everything from module 2 is due before the second class on the 18th, and everything in the 3rd module is due before the 3rd class on the 25th.  The only exceptions to this are the build your own BDA assignment which I listed as due before the second class, and the primary assignment which I listed as due on Feb 1st, 1 week after the 3rd class.  Is this correct?

**Comment by joewheaton** [comment]
> @joewheaton I've changed them so that everything from Module 1 (lectures, readings, and quiz) are all due before the first class on the 11th, everything from module 2 is due before the second class on the 18th, and everything in the 3rd module is due before the 3rd class on the 25th. The only exceptions to this are the build your own BDA assignment which I listed as due before the second class, and the primary assignment which I listed as due on Feb 1st, 1 week after the 3rd class. Is this correct?

Mostly. I'm moving the BDA assignment to after Week 2 and adding an extra week on primary assignment.

**Comment by dominique-shore** [comment]
Semester ended
